name: Deploy Armageddon App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm i

      - name: Build project
        run: npm run build

      - name: Check files
        run: ls .

      - name: Check current directory
        run: pwd

      - name: Deploy to GHPages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./dist

        
      - name: change directory
        run: ls dist