name: Deploy Armageddon App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: action/checkout@v4

      - name: Say hello
        run: echo "Say something from WORKFLOW"