name: Deploy Armageddon App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Node version
        run: node --version

      - name: Install Dependencies
        run: npm i

      - name: Run unit tests
        run: npm run test:unit

      - name: Build project
        run: npm run build

      - name: Check files
        run: ls .

      - name: change directory
        run: ls dist

      - name: Deploy to GHPages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./dist
          enable_jekyll: false
          keep_files: false
      
      - name: change directory
        run: ls dist