name: Deploy Armageddon App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        uses: echo "Say something from WORKFLOW"